title: Tobias Dörrich (formerly Johansson) - Level Designer
description: > # this means to ignore newlines until "baseurl:"
  Lead Level Designer at Gunzilla Games
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "https://tobiasdoerrich.com/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tobias Dörrich (formerly Johansson)
author-img: tobias-profile.png 
about-author: I’m a game developer and level designer with experience working across AAA and independent projects, from early concept and prototyping through to production and release. Over the years I’ve worked in senior and lead level design roles on projects including Star Citizen, OFF THE GRID, Dune Awakening, Exoborne, and SNOW. I’m currently based near Munich, Germany, and am looking for my next opportunity in game development or a related field.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: TobiasDev # add your Github handle
social-linkedin: tobias-d%C3%B6rrich-formerly-johansson-25213033 # add your Linkedin handle
social-email: contact@tobiasdoerrich.com # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
